-- AlterTable
ALTER TABLE "OrderEarnings" ALTER COLUMN "federico" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "oscar" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sub" SET DATA TYPE DOUBLE PRECISION;
